# CORRETO ✅
name: quiz_flutter
description: Quiz Raul Seixas

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mockup/perguntas.json